### ISSUE TITLE
BUG: liste med bugs i concept-catalog

### ISSUE THREAD

**Issue by pooriamehregan** [Informasjonsforvaltning/catalog-frontend#283]
## 🐛 Bug rapport

- [x] Tilbakeknappen går ikke tilbake fra detalj-siden til treff-siden
- [x] Logoen er for stor
- [x] Status vises ikke riktig
- [x] Lagre som utkast-knappen fungerer ikke som det skal
- [x] Endringshistorikk på detaljsiden er ikke ferdig implementert

### Sjekkliste (Sjekk av etter issue er laget)

- [x] Lagt til label for app: admin, concept, e.l.
- [x] Lagt i utviklingsbrettet (Project)
